services:
  site:
    image: gustavoalvesdeoliveira/site-zephyrus:latest
    ports:
      - "3333:3333"
    networks:
      - rede-zephyrus
    depends_on:
      - db-zephyrus

  db-zephyrus:
    image: gustavoalvesdeoliveira/db-zephyrus:latest
    ports:
      - "3306:3306"
    networks:
      - rede-zephyrus
    volumes:
      - zephyrus_data:/var/lib/mysql
volumes:
  zephyrus_data:

networks:
  rede-zephyrus:
    driver: bridge
